---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: linux
    image: diodonfrost/${distribution:-ansible-centos:8}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    env:
      python_version: "${python_version:-3.8.5}"
provisioner:
  name: ansible
verifier:
  name: ansible
